### ISSUE TITLE
Would it make sense to use Diesel for building the SQL queries?

### ISSUE THREAD

**Issue by WildYorkies** [datafusion-rs/datafusion-rs#16]
http://diesel.rs/

**Comment by andygrove** [comment]
Probably, yes.

I'm going to stick with my current approach while I build out the initial POC because it is a style I am familiar with and can move fast (in the limited amount of weekend/evening time I can commit to this project at the moment).

If I do move to diesel to represent relational plans then I do have some requirements ... I don't know if diesel supports them or not currently ...

- UDT support
- Partition-aware relations
- Ability to serialize relational plans to JSON
- Ability to represent lambda/closure style operations (eventually)

I'll definitely revisit this when I'm a little further along.

**Comment by andygrove** [comment]
I think Diesel is a query builder that generates SQL, whereas DataFusion needs to parse SQL so I actually don't think this is a good fit as this time.
